### ISSUE TITLE
[Feature Request] make this work with rethinking voxels

### ISSUE THREAD

**Issue by Aaroneisele55** [EuphoriaPatches/Changelogs#1]
Hello,
I am currently using Complementary shaders with Euphoria Patches, but I would like to use [Rethinking Voxels](https://modrinth.com/shader/rethinking-voxels) because of its better lighting calculations (Raytracing), which Complementary doesn't have.

Is there any way to make Euphoria Patches work with rethinking Voxels?
Please answer as soon as possible

Greetings
Aaron

**Comment by SpacEagle17** [comment]
There is no way to do that yet and probably also not in the future unfortuantely
