### ISSUE TITLE
World Curvature Causes Enchantment Glint Flickering

### ISSUE THREAD

**Issue by MaidScientistIzutsumiMarin** [EuphoriaPatches/Changelogs#3]
When the Word Curvature setting is enabled under the Fun category, it causes enchantment glint on items to flicker a lot. This happens when you turn the camera in any direction.

I have the latest version of all mods installed and Complementary Unbounded. This happens with the default settings with only World Curvature turned on.

**Comment by SpacEagle17** [comment]
World curvature is a fun setting and should not be used during normal gameplay, I can't/won't fix any issues with it
